name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Generate release tag
        id: tag
        run: echo ::set-output name=release_tag::$(date +'%Y%m%d%H%M%S')
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/sc_blog_salvo/sc_blog_salvo/target/release/sc_blog_salvo
          tag_name: ${{ steps.tag.outputs.release_tag }}